I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 46, in script
    with fadr
  File "game/script.rpy", line 46, in <module>
    with fadr
NameError: name 'fadr' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 46, in script
    with fadr
  File "/home/minqwq/renpy-8.3.2-sdkarm/renpy/ast.py", line 1354, in execute
    trans = renpy.python.py_eval(self.expr)
  File "/home/minqwq/renpy-8.3.2-sdkarm/renpy/python.py", line 1209, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "/home/minqwq/renpy-8.3.2-sdkarm/renpy/python.py", line 1202, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 46, in <module>
    with fadr
NameError: name 'fadr' is not defined

Linux-4.14.186-perf-00243-g9a0d96109bda-aarch64-with-glibc2.36 aarch64
Ren'Py 8.3.2.24090902
minqwq's life 1.0(dev release 1)
Tue Nov 12 05:57:30 2024
